# Generated by Django 6.0.1 on 2026-01-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(blank=True, help_text='Job role/position', max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL', max_length=500)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated skills')),
                ('experience_years', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('match_score', models.FloatField(default=0.0)),
                ('ai_reasoning', models.TextField(blank=True, help_text='AI-generated reasoning for match')),
                ('ai_highlights', models.TextField(blank=True, help_text='JSON array of highlights')),
                ('ai_concerns', models.TextField(blank=True, help_text='JSON array of concerns')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-match_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('records_imported', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Upload Histories',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
