# Generated by Django 6.0.1 on 2026-01-23 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='ai_concerns',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='ai_highlights',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='ai_reasoning',
        ),
    ]
